export default [
  {value:0,label:'Aachen [Aix-la-Chapelle]',state:'NW'},
  {value:1,label:'Aalen',state:'BW'},
  {value:2,label:'Ahlen',state:'NW'},
  {value:3,label:'Arnsberg',state:'NW'},
  {value:4,label:'Aschaffenburg',state:'BY'},
  {value:5,label:'Augsburg',state:'BY'},
  {value:6,label:'Baden-Baden',state:'BW'},
  {value:7,label:'Bad Homburg (Bad Homburg vor der Höhe)',state:'HE'},
  {value:8,label:'Bad Salzuflen',state:'NW'},
  {value:9,label:'Bamberg',state:'BY'},
  {value:10,label:'Bayreuth',state:'BY'},
  {value:11,label:'Bergheim',state:'NW'},
  {value:12,label:'Bergisch Gladbach',state:'NW'},
  {value:13,label:'Berlin',state:'BE'},
  {value:14,label:'Bielefeld',state:'NW'},
  {value:15,label:'Bocholt',state:'NW'},
  {value:16,label:'Bochum',state:'NW'},
  {value:17,label:'Bonn',state:'NW'},
  {value:18,label:'Bottrop',state:'NW'},
  {value:19,label:'Brandenburg an der Havel',state:'BB'},
  {value:20,label:'Braunschweig[Brunswick]',state:'NI'},
  {value:21,label:'Bremen',state:'HB'},
  {value:22,label:'Bremerhaven',state:'HB'},
  {value:23,label:'Castrop-Rauxel',state:'NW'},
  {value:24,label:'Celle',state:'NI'},
  {value:25,label:'Chemnitz',state:'SN'},
  {value:26,label:'Cottbus (Chóśebuz)',state:'BB'},
  {value:27,label:'Darmstadt',state:'HE'},
  {value:28,label:'Delmenhorst',state:'NI'},
  {value:29,label:'Dessau-Roßlau',state:'ST'},
  {value:30,label:'Detmold',state:'NW'},
  {value:31,label:'Dinslaken',state:'NW'},
  {value:32,label:'Dormagen',state:'NW'},
  {value:33,label:'Dorsten',state:'NW'},
  {value:34,label:'Dortmund',state:'NW'},
  {value:35,label:'Dresden',state:'SN'},
  {value:36,label:'Duisburg',state:'NW'},
  {value:37,label:'Düren',state:'NW'},
  {value:38,label:'Düsseldorf [Dusseldorf]',state:'NW'},
  {value:39,label:'Emden',state:'NI'},
  {value:40,label:'Erfurt',state:'TH'},
  {value:41,label:'Erlangen',state:'BY'},
  {value:42,label:'Eschweiler',state:'NW'},
  {value:43,label:'Essen',state:'NW'},
  {value:44,label:'Esslingen am Neckar',state:'BW'},
  {value:45,label:'Euskirchen',state:'NW'},
  {value:46,label:'Flensburg',state:'SH'},
  {value:47,label:'Frankfurt (Oder)',state:'BB'},
  {value:48,label:'Frankfurt am Main',state:'HE'},
  {value:49,label:'Frechen',state:'NW'},
  {value:50,label:'Freiburg (Freiburg im Breisgau)',state:'BW'},
  {value:51,label:'Friedrichshafen',state:'BW'},
  {value:52,label:'Fulda',state:'HE'},
  {value:53,label:'Fürth',state:'BY'},
  {value:54,label:'Garbsen',state:'NI'},
  {value:55,label:'Gelsenkirchen',state:'NW'},
  {value:56,label:'Gera',state:'TH'},
  {value:57,label:'Gießen',state:'HE'},
  {value:58,label:'Gladbeck',state:'NW'},
  {value:59,label:'Göppingen',state:'BW'},
  {value:60,label:'Görlitz',state:'SN'},
  {value:61,label:'Goslar',state:'NI'},
  {value:62,label:'Göttingen',state:'NI'},
  {value:63,label:'Greifswald',state:'MV'},
  {value:64,label:'Grevenbroich',state:'NW'},
  {value:65,label:'Gütersloh',state:'NW'},
  {value:66,label:'Hagen',state:'NW'},
  {value:67,label:'Halle (Saale)',state:'ST'},
  {value:68,label:'Hamburg',state:'HH'},
  {value:69,label:'Hameln',state:'NI'},
  {value:70,label:'Hamm',state:'NW'},
  {value:71,label:'Hanau',state:'HE'},
  {value:72,label:'Hannover [Hanover]',state:'NI'},
  {value:73,label:'Hattingen',state:'NW'},
  {value:74,label:'Heidelberg',state:'BW'},
  {value:75,label:'Heilbronn',state:'BW'},
  {value:76,label:'Herford',state:'NW'},
  {value:77,label:'Herne',state:'NW'},
  {value:78,label:'Herten',state:'NW'},
  {value:79,label:'Hilden',state:'NW'},
  {value:80,label:'Hildesheim',state:'NI'},
  {value:81,label:'Hürth',state:'NW'},
  {value:82,label:'Ibbenbüren',state:'NW'},
  {value:83,label:'Ingolstadt',state:'BY'},
  {value:84,label:'Iserlohn',state:'NW'},
  {value:85,label:'Jena',state:'TH'},
  {value:86,label:'Kaiserslautern',state:'RP'},
  {value:87,label:'Karlsruhe',state:'BW'},
  {value:88,label:'Kassel',state:'HE'},
  {value:89,label:'Kempten (Allgäu)',state:'BY'},
  {value:90,label:'Kerpen',state:'NW'},
  {value:91,label:'Kiel',state:'SH'},
  {value:92,label:'Koblenz',state:'RP'},
  {value:93,label:'Köln [Cologne]',state:'NW'},
  {value:94,label:'Konstanz',state:'BW'},
  {value:95,label:'Krefeld',state:'NW'},
  {value:96,label:'Landshut',state:'BY'},
  {value:97,label:'Langenfeld (Rheinland)',state:'NW'},
  {value:98,label:'Langenhagen',state:'NI'},
  {value:99,label:'Leipzig',state:'SN'},
  {value:100,label:'Leverkusen',state:'NW'},
  {value:101,label:'Lingen (Ems)',state:'NI'},
  {value:102,label:'Lippstadt',state:'NW'},
  {value:103,label:'Lübeck',state:'SH'},
  {value:104,label:'Lüdenscheid',state:'NW'},
  {value:105,label:'Ludwigsburg',state:'BW'},
  {value:106,label:'Ludwigshafen(Ludwigshafen am Rhein)',state:'RP'},
  {value:107,label:'Lüneburg',state:'NI'},
  {value:108,label:'Lünen',state:'NW'},
  {value:109,label:'Magdeburg',state:'ST'},
  {value:110,label:'Mainz',state:'RP'},
  {value:111,label:'Mannheim',state:'BW'},
  {value:112,label:'Marburg',state:'HE'},
  {value:113,label:'Marl',state:'NW'},
  {value:114,label:'Meerbusch',state:'NW'},
  {value:115,label:'Menden (Sauerland)',state:'NW'},
  {value:116,label:'Minden',state:'NW'},
  {value:117,label:'Moers',state:'NW'},
  {value:118,label:'Mönchengladbach',state:'NW'},
  {value:119,label:'Mülheim an der Ruhr',state:'NW'},
  {value:120,label:'München [Munich]',state:'BY'},
  {value:121,label:'Münster',state:'NW'},
  {value:122,label:'Neubrandenburg',state:'MV'},
  {value:123,label:'Neumünster',state:'SH'},
  {value:124,label:'Neuss',state:'NW'},
  {value:125,label:'Neustadt an der Weinstraße',state:'RP'},
  {value:126,label:'Neu-Ulm',state:'BY'},
  {value:127,label:'Neuwied',state:'RP'},
  {value:128,label:'Norderstedt',state:'SH'},
  {value:129,label:'Nordhorn',state:'NI'},
  {value:130,label:'Nürnberg [Nuremberg]',state:'BY'},
  {value:131,label:'Oberhausen',state:'NW'},
  {value:132,label:'Offenbach am Main',state:'HE'},
  {value:133,label:'Offenburg',state:'BW'},
  {value:134,label:'Oldenburg (Oldenburg)',state:'NI'},
  {value:135,label:'Osnabrück',state:'NI'},
  {value:136,label:'Paderborn',state:'NW'},
  {value:137,label:'Pforzheim',state:'BW'},
  {value:138,label:'Plauen',state:'SN'},
  {value:139,label:'Potsdam',state:'BB'},
  {value:140,label:'Pulheim',state:'NW'},
  {value:141,label:'Ratingen',state:'NW'},
  {value:142,label:'Recklinghausen',state:'NW'},
  {value:143,label:'Regensburg',state:'BY'},
  {value:144,label:'Remscheid',state:'NW'},
  {value:145,label:'Reutlingen',state:'BW'},
  {value:146,label:'Rheine',state:'NW'},
  {value:147,label:'Rosenheim',state:'BY'},
  {value:148,label:'Rostock',state:'MV'},
  {value:149,label:'Rüsselsheim am Main',state:'HE'},
  {value:150,label:'Saarbrücken',state:'SL'},
  {value:151,label:'Salzgitter',state:'NI'},
  {value:152,label:'Sankt Augustin',state:'NW'},
  {value:153,label:'Schwäbisch Gmünd',state:'BW'},
  {value:154,label:'Schweinfurt',state:'BY'},
  {value:155,label:'Schwerin',state:'MV'},
  {value:156,label:'Siegen',state:'NW'},
  {value:157,label:'Sindelfingen',state:'BW'},
  {value:158,label:'Solingen',state:'NW'},
  {value:159,label:'Stolberg (Rheinland)',state:'NW'},
  {value:160,label:'Stralsund',state:'MV'},
  {value:161,label:'Stuttgart',state:'BW'},
  {value:162,label:'Trier',state:'RP'},
  {value:163,label:'Troisdorf',state:'NW'},
  {value:164,label:'Tübingen',state:'BW'},
  {value:165,label:'Ulm',state:'BW'},
  {value:166,label:'Unna',state:'NW'},
  {value:167,label:'Velbert',state:'NW'},
  {value:168,label:'Viersen',state:'NW'},
  {value:169,label:'Villingen-Schwenningen',state:'BW'},
  {value:170,label:'Waiblingen',state:'BW'},
  {value:171,label:'Weimar',state:'TH'},
  {value:172,label:'Wesel',state:'NW'},
  {value:173,label:'Wetzlar',state:'HE'},
  {value:174,label:'Wiesbaden',state:'HE'},
  {value:175,label:'Wilhelmshaven',state:'NI'},
  {value:176,label:'Willich',state:'NW'},
  {value:177,label:'Witten',state:'NW'},
  {value:178,label:'Wolfenbüttel',state:'NI'},
  {value:179,label:'Wolfsburg',state:'NI'},
  {value:180,label:'Worms',state:'RP'},
  {value:181,label:'Wuppertal',state:'NW'},
  {value:182,label:'Würzburg',state:'BY'},
  {value:183,label:'Zwickau',state:'BY'},
]


