export default [
  {value:0,label:'Aachen'},
  {value:1,label:'Aalen'},
  {value:2,label:'Ahlen'},
  {value:3,label:'Arnsberg'},
  {value:4,label:'Aschaffenburg'},
  {value:5,label:'Augsburg'},
  {value:6,label:'Bad Homburg'},
  {value:7,label:'Bad Salzuflen'},
  {value:8,label:'Baden-Baden'},
  {value:9,label:'Bamberg'},
  {value:10,label:'Bayreuth'},
  {value:11,label:'Bergheim'},
  {value:12,label:'Bergisch Gladbach'},
  {value:13,label:'Berlin'},
  {value:14,label:'Bielefeld'},
  {value:15,label:'Bocholt'},
  {value:16,label:'Bochum'},
  {value:17,label:'Bonn'},
  {value:18,label:'Bottrop'},
  {value:19,label:'Brandenburg an der Havel'},
  {value:20,label:'Braunschweig'},
  {value:21,label:'Bremen'},
  {value:22,label:'Bremerhaven'},
  {value:23,label:'Castrop-Rauxel'},
  {value:24,label:'Celle'},
  {value:25,label:'Chemnitz'},
  {value:26,label:'Cottbus'},
  {value:27,label:'Darmstadt'},
  {value:28,label:'Delmenhorst'},
  {value:29,label:'Dessau-Roßlau'},
  {value:30,label:'Detmold'},
  {value:31,label:'Dinslaken'},
  {value:32,label:'Dormagen'},
  {value:33,label:'Dorsten'},
  {value:34,label:'Dortmund'},
  {value:35,label:'Dresden'},
  {value:36,label:'Duisburg'},
  {value:37,label:'Düren'},
  {value:38,label:'Düsseldorf'},
  {value:39,label:'Emden'},
  {value:40,label:'Erfurt'},
  {value:41,label:'Erlangen'},
  {value:42,label:'Eschweiler'},
  {value:43,label:'Essen'},
  {value:44,label:'Esslingen am Neckar'},
  {value:45,label:'Euskirchen'},
  {value:46,label:'Flensburg'},
  {value:47,label:'Frankfurt (Oder)'},
  {value:48,label:'Frankfurt am Main'},
  {value:49,label:'Frechen'},
  {value:50,label:'Freiburg'},
  {value:51,label:'Friedrichshafen'},
  {value:52,label:'Fulda'},
  {value:53,label:'Fürth'},
  {value:54,label:'Garbsen'},
  {value:55,label:'Gelsenkirchen'},
  {value:56,label:'Gera'},
  {value:57,label:'Gießen'},
  {value:58,label:'Gladbeck'},
  {value:59,label:'Göppingen'},
  {value:60,label:'Görlitz'},
  {value:61,label:'Goslar'},
  {value:62,label:'Göttingen'},
  {value:63,label:'Greifswald'},
  {value:64,label:'Grevenbroich'},
  {value:65,label:'Gütersloh'},
  {value:66,label:'Hagen'},
  {value:67,label:'Halle (Saale)'},
  {value:68,label:'Hamburg'},
  {value:69,label:'Hameln'},
  {value:70,label:'Hamm'},
  {value:71,label:'Hanau'},
  {value:72,label:'Hannove'},
  {value:73,label:'Hattingen'},
  {value:74,label:'Heidelberg'},
  {value:75,label:'Heilbronn'},
  {value:76,label:'Herford'},
  {value:77,label:'Herne'},
  {value:78,label:'Herten'},
  {value:79,label:'Hilden'},
  {value:80,label:'Hildesheim'},
  {value:81,label:'Hürth'},
  {value:82,label:'Ibbenbüren'},
  {value:83,label:'Ingolstadt'},
  {value:84,label:'Iserlohn'},
  {value:85,label:'Jena'},
  {value:86,label:'Kaiserslautern'},
  {value:87,label:'Karlsruhe'},
  {value:88,label:'Kassel'},
  {value:89,label:'Kempten (Allgäu)'},
  {value:90,label:'Kerpen'},
  {value:91,label:'Kiel'},
  {value:92,label:'Koblenz'},
  {value:93,label:'Köln (Cologne)'},
  {value:94,label:'Konstanz'},
  {value:95,label:'Krefeld'},
  {value:96,label:'Landshut'},
  {value:97,label:'Langenfeld (Rheinland)'},
  {value:98,label:'Langenhagen'},
  {value:99,label:'Leipzig'},
  {value:100,label:'Leverkusen'},
  {value:101,label:'Lingen (Ems)'},
  {value:102,label:'Lippstadt'},
  {value:103,label:'Lübeck'},
  {value:104,label:'Lüdenscheid'},
  {value:105,label:'Ludwigsburg'},
  {value:106,label:'Ludwigshafen(Ludwigshafen am Rhein)'},
  {value:107,label:'Lüneburg'},
  {value:108,label:'Lünen'},
  {value:109,label:'Magdeburg'},
  {value:110,label:'Mainz'},
  {value:111,label:'Mannheim'},
  {value:112,label:'Marburg'},
  {value:113,label:'Marl'},
  {value:114,label:'Meerbusch'},
  {value:115,label:'Menden (Sauerland)'},
  {value:116,label:'Minden'},
  {value:117,label:'Moers'},
  {value:118,label:'Mönchengladbach'},
  {value:119,label:'Mülheim an der Ruhr'},
  {value:120,label:'München(Munich)'},
  {value:121,label:'Münster'},
  {value:122,label:'Name'},
  {value:123,label:'Neu-Ulm'},
  {value:124,label:'Neubrandenburg'},
  {value:125,label:'Neumünster'},
  {value:126,label:'Neuss'},
  {value:127,label:'Neustadt an der Weinstraße'},
  {value:128,label:'Neuwied'},
  {value:129,label:'Norderstedt'},
  {value:130,label:'Nordhorn'},
  {value:131,label:'Nürnberg [Nuremberg]'},
  {value:132,label:'Oberhausen'},
  {value:133,label:'Offenbach am Main'},
  {value:134,label:'Offenburg'},
  {value:135,label:'Oldenburg'},
  {value:136,label:'Osnabrück'},
  {value:137,label:'Paderborn'},
  {value:138,label:'Pforzheim'},
  {value:139,label:'Plauen'},
  {value:140,label:'Potsdam'},
  {value:141,label:'Pulheim'},
  {value:142,label:'Ratingen'},
  {value:143,label:'Recklinghausen'},
  {value:144,label:'Regensburg'},
  {value:145,label:'Remscheid'},
  {value:146,label:'Reutlingen'},
  {value:147,label:'Rheine'},
  {value:148,label:'Rosenheim'},
  {value:149,label:'Rostock'},
  {value:150,label:'Rüsselsheim am Main'},
  {value:151,label:'Saarbrücken'},
  {value:152,label:'Salzgitter'},
  {value:153,label:'Sankt Augustin'},
  {value:154,label:'Schwäbisch Gmünd'},
  {value:155,label:'Schweinfurt'},
  {value:156,label:'Schwerin'},
  {value:157,label:'Siegen'},
  {value:158,label:'Sindelfingen'},
  {value:159,label:'Solingen'},
  {value:160,label:'Stolberg(Rheinland)'},
  {value:161,label:'Stralsund'},
  {value:162,label:'Stuttgart'},
  {value:163,label:'Trier'},
  {value:164,label:'Troisdorf'},
  {value:165,label:'Tübingen'},
  {value:166,label:'Ulm'},
  {value:167,label:'Unna'},
  {value:168,label:'Velbert'},
  {value:169,label:'Viersen'},
  {value:170,label:'Villingen-Schwenningen'},
  {value:171,label:'Waiblingen'},
  {value:172,label:'Weimar'},
  {value:173,label:'Wesel'},
  {value:174,label:'Wetzlar'},
  {value:175,label:'Wiesbaden'},
  {value:176,label:'Wilhelmshaven'},
  {value:177,label:'Willich'},
  {value:178,label:'Witten'},
  {value:179,label:'Wolfenbüttel'},
  {value:180,label:'Wolfsburg'},
  {value:181,label:'Worms'},
  {value:182,label:'Wuppertal'},
  {value:183,label:'Würzburg'},
  {value:184,label:'Zwickau'},
]


